# --- API ---
server.port=${PORT:8080}
server.forward-headers-strategy=${FORWARD_HEADERS_STRATEGY}
spring.mvc.problemdetails.enabled=${MVC_PROBLEMDTLS_ENABLED}
spring.web.error.include-stacktrace=${WEB_ERROR_INCLUDE_STACKTRACE}

# --- Seguridad HTTP
app.security.hsts-enabled=${SECURITY_HSTS_ENABLED}
app.security.login-rate-limit-per-minute=${LOGIN_RATE_LIMIT}

# --- Persistencia
spring.jpa.open-in-view=${JPA_OPEN_IN_VIEW}
spring.jpa.properties.hibernate.jdbc.time_zone=${HIBERNATE_TIME_ZONE}

# JPA
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${JPA_HBM2DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}

# --- JWT 
app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-ttl-seconds=${JWT_ACCESS_TOKEN_TTL_SECONDS}
app.jwt.refresh-token-ttl-seconds=${JWT_REFRESH_TOKEN_TTL_SECONDS}


# --- OpenAPI / Swagger
springdoc.api-docs.path=${APIDOCS_PATH}
springdoc.swagger-ui.path=${SWAGGER_UI_PATH}

# --- Logs
logging.pattern.console=${LOGGING_PATTERN_CONSOLE:%d{yyyy-MM-dd HH:mm:ss} - %msg%n}

management.endpoints.web.exposure.include=health,prometheus,info
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.metrics.tags.application=authentication-service


